{% set name = "mecademicpy" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mecademicpy-{{ version }}.tar.gz
  sha256: 1c84db29ad27bd83231c386c0b7f6f3cf0e57dfcd7b4067196ebb51cde5f7bb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dataclasses-json >=0.5.4
    - deprecation
    - pandas
    - requests
    - pyyaml

test:
  imports:
    - mecademicpy
    - mecademicpy.robot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.mecademic.com/support/
  dev_url: https://github.com/Mecademic/mecademicpy
  summary: A package to control the Mecademic robots through python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
