{% set name = "mecademicpy" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mecademicpy-{{ version }}.tar.gz
  sha256: 972818826671af54d4222b840315fb067f3f2f4f657d3cf381e785f34b25d261

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dataclasses-json >=0.5.4
    - deprecation
    - pandas
    - requests
    - pyyaml

test:
  imports:
    - mecademicpy
    - mecademicpy.robot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.mecademic.com/support/
  dev_url: https://github.com/Mecademic/mecademicpy
  summary: A package to control the Mecademic robots through python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
