{% set name = "mecademicpy" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mecademicpy-{{ version }}.tar.gz
  sha256: 5418681a4ea2c5dd42ad0cfdb6ccd3b3bdfdd85e6a05b23aa0b2083dd2c38fc8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - dataclasses-json >=0.5.4
    - deprecation
    - pandas
    - requests
    - pyyaml

test:
  imports:
    - mecademicpy
    - mecademicpy.robot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.mecademic.com/support/
  dev_url: https://github.com/Mecademic/mecademicpy
  summary: A package to control the Mecademic robots through python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jjerphan
